PROCEDURE WriteStyle_SnowFlake;
BEGIN  
  Write (T, '<style>');
  Write (T, 'body {');
  Write (T, 'overflow-x: hidden;');
  Write (T, 'height: 100%;');
  Write (T, 'margin: 0;');
  Write (T, 'padding: 0;');
  Write (T, '}');
  Write (T, '.snowflake {');
  Write (T, 'position: fixed;');
  Write (T, 'top: -10px;');
  Write (T, 'animation: snowfall linear infinite;');
  Write (T, '}');
  Write (T, '@keyframes snowfall {');
  Write (T, 'from {');
  Write (T, 'transform: translateY(-10px) translateX(0);');
  Write (T, '}');
  Write (T, 'to {');
  Write (T, 'transform: translateY(100vh) translateX(0);');
  Write (T, '}');
  Write (T, '}');
  Write (T, '</style>');
  WriteLn (T);
END;

PROCEDURE WriteStyle_Blink;
BEGIN  
  Write (T, '<style>');
  Write (T, '@keyframes blink ');
  Write (T, '{');
  Write (T, '0% {opacity: 1;}');
  Write (T, '50% {opacity: 0;}');
  Write (T, '100% {opacity: 1;}');
  Write (T, '}');
  Write (T);
  Write (T, '.blinking-text {');
  Write (T, 'text-align: center;');
  Write (T, 'animation: blink 1s infinite;');
  Write (T, '}');
  Write (T, '</style>');
  WriteLn (T);
END;

PROCEDURE WriteStyle_TableHighlight;
BEGIN
  Write (T);
  Write (T, '<style>');
  Write (T, '.myTable {}');
  Write (T, '.myTable thead th {}');
  Write (T, '.myTable tbody td {}');
  Write (T);
  Write (T, '.myTable-highlight-all {');
  Write (T, 'overflow: hidden;');
  Write (T, 'z-index: 1;');
  Write (T, '}');
  Write (T);
  Write (T, '.myTable-highlight-all tbody td, .myTable-highlight-all thead th {');
  Write (T, 'position: relative;');
  Write (T, '}');
  Write (T);
  Write (T, '.myTable-highlight-all tbody td:hover::before {');
  Write (T, 'background-color: ', Highlight_BGColor, ';');
  Write (T, 'content:''\00a0'';');
  Write (T, 'height: 100%;');
  Write (T, 'left: -5000px;');
  Write (T, 'position: absolute;');
  Write (T, 'top: 0;');
  Write (T, 'width: 10000px;');
  Write (T, 'z-index: -1;');
  Write (T, '}');
  Write (T);
  Write (T, 'a:link {');
  Write (T, 'color: ', CSS_Link_Color, ';');
  Write (T, '}');
  Write (T);
  Write (T, 'a:visited {');
  Write (T, 'color: ', CSS_VLink_Color, ';');
  Write (T, '}');
  Write (T, '</style>');
  Write (T);
END;
